### ISSUE TITLE
Example does not compile

### ISSUE THREAD

**Issue by iLandes** [ivanbruel/MarkdownKit#2]
Hello,

I'm just trying to use your code. I download Example project but I have a compilation Error

ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/Developer/Library/Frameworks'

Can you please help

**Comment by ivanbruel** [comment]
Are you using the most recent Xcode 7 (7.3.1 - 7D1014)?

**Comment by iLandes** [comment]
Yes I

**Comment by ivanbruel** [comment]
As I cannot replicate the issue, can you have a look at http://stackoverflow.com/questions/30827022/xcode-7-library-search-path-warning/32620919#32620919 and let me know if that helps?

**Comment by iLandes** [comment]
Hello,

I'm back and I trying your example after few weeks of holidays

I found the solution. ;-)

You may convert your project from Xcode 6 to Xcode 7 (don't you ?). After visiting apple official developper forum here

I delete Search path line (see picture). The example works fine now.

I thing you have to change this in your project for next user of your code

![capture d ecran 2016-09-03 a 18 27 50](https://cloud.githubusercontent.com/assets/6915996/18226176/910b141e-7204-11e6-9963-3df9bc6d2619.png)

regards,
Seb

**Comment by ivanbruel** [comment]
I deleted it from my Test target, hopefully no one else will have to face this issue, thanks!
