### ISSUE TITLE
Carthage support please

### ISSUE THREAD

**Issue by antonioreyna** [ivanbruel/MarkdownKit#3]
Hello, please make it Carthage able :)

**Comment by ivanbruel** [comment]
I've yet to ever use Carthage, but feel free to make a pull request if you're familiar with it!

**Comment by antonioreyna** [comment]
ill try thanks! i have another question, how would i set the normal font size and family? and for example the h1 styles and the h2 styles?

thanks

**Comment by ivanbruel** [comment]
Hey there, setting a default font size can now be done in `let markdownParser = MarkdownParser(font: UIFont.systemFontOfSize(20))`, otherwise, you can do it like:
 ```swift
markdownParser.header.font = UIFont.systemFontOfSize(30) // H1 font size
markdownParser.header.fontIncrease = 3 // H2 font size = 33, H3 = 36, H4 = 39, etc
```

**Comment by ivanbruel** [comment]
Leaving this open until we have Carthage support

**Comment by chrisdhaan** [comment]
@ivanbruel I'll create a PR enabling carthage support tonight

**Comment by chrisdhaan** [comment]
@ivanbruel thanks for merging in the PR! Glad to have helped. I believe this issue can now be closed.

**Comment by ivanbruel** [comment]
Thank you for the contribution @chrisdhaan! Closing this 👍
